accounts/urls.py
from django.urls import path
from django.contrib.auth.views import login, logout
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', login, name = 'login', kwargs = {
        'template_name' : 'accounts/login_form.html',
    }),
    path('logout/', logout, name = 'logout', kwargs = {
        'next_page' : '/',
    }),
    path('signup/', views.signup, name = 'signup'),
    path('profile/', views.profile, name = 'profile'),
]

musics/urls.py
from django.urls import path
from . import views

app_name = 'musics'
urlpatterns = [
    path('', views.list, name = 'list'),
    path('mdetail/<str:id>', views.mdetail, name = 'mdetail'),
    path('detail/<int:id>', views.detail, name = 'detail'),
    path('detail/<int:id>/save_comment/', views.save_comment, name = 'save_comment'),
]

portalsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('musics.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, related_name = 'profile', on_delete = models.CASCADE)
    bio = models.TextField(blank = True)
    location = models.CharField(max_length = 30, blank = True)
    birth_at = models.DateField(null = True, blank = True)

@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

@receiver(post_save, sender = User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

musics/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Musician(models.Model):
    name = models.CharField(max_length = 100)
    debut_at = models.DateField(null = True, blank = True)
    agency = models.CharField(max_length = 100, null = True, blank = True)
    introduction = models.TextField(null = True, blank = True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length = 100)
    musician = models.ForeignKey(Musician, on_delete = models.CASCADE)
    cover = models.ImageField()
    release_at = models.DateField()
    genre = models.CharField(max_length = 20)
    distribution = models.CharField(max_length = 20)
    introduction = models.TextField()
    is_public = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100)
    musician = models.CharField(max_length = 50)
    order = models.IntegerField(default = 1)
    lyrics = models.TextField(null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.message

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        if email:
            if get_user_model().objects.filter(email = email).exists():
                raise forms.ValidationError('존재하는 이메일 주소입니다.')
        return email

# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_at')

musics/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

accounts/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from .forms import SignupForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup_form.html', {
        'form' : form,
    })

def profile(request):
    return render(request, 'accounts/profile.html')

musics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Musician, Album, Song, Comment
from django.contrib.auth.decorators import login_required
from .forms import CommentForm

# Create your views here.
def list(request):
    albums = Album.objects.all()
    context = {'albums' : albums}
    return render(request, 'musics/list.html', context)

def mdetail(request, id):
    musician = Musician.objects.get(name = id)
    albums = Album.objects.filter(musician = musician.id)
    context = {
        'musician' : musician,
        'albums' : albums,
    }
    return render(request, 'musics/mdetail.html', context)

def detail(request, id):
    album = Album.objects.get(id = id)
    songs = Song.objects.filter(album = id)
    # comments = Comment.objects.all().order_by('-id')[:10]
    comments = Comment.objects.filter(album = id)
    form = CommentForm()
    context = {
        'album' : album,
        'songs' : songs,
        'comments' : comments,
        'form' : form,
    }
    return render(request, 'musics/detail.html', context)

@login_required
def save_comment(request, id):
    # album = get_object_or_404(Album, pk = id)
    album = Album.objects.get(id = id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.album = album
            comment.user = request.user
            comment.save()
            return redirect('musics:detail', album.pk)
    else:
        form = CommentForm()
    return render(request, 'musics/detail.html', {'form' : form})

accounts/templates/accounts/layout.html
{% extends 'layout.html' %}

accounts/templates/accounts/login_form.html
{% extends 'accounts/layout.html' %}
{% block content %}
<nav>
    <div class="nav-wrapper" style="margin-left: 16px;">
        <div class="col">
            <a href="/" class="breadcrumb"><i class="material-icons">home</i></a>
            <span class="breadcrumb">로그인</span>
        </div>
    </div>
</nav>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">로그인</span>
        <form method="post">
            {% csrf_token %}
            <table style="margin-bottom: 8px;">
                {{form.as_table}}
            </table>
            <button type="submit" class="btn">확인</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layout.html' %}
{% block content %}
<nav>
    <div class="nav-wrapper" style="margin-left: 16px;">
        <div class="col">
            <a href="/" class="breadcrumb"><i class="material-icons">home</i></a>
            <span class="breadcrumb">마이페이지</span>
        </div>
    </div>
</nav>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">마이페이지</span>
        <table>
            <tr>
                <th>아이디</th>
                <td>{{user.username}}</td>
            </tr>
            <tr>
                <th>이메일</th>
                <td>{{user.email}}</td>
            </tr>
            <tr>
                <th>가입일</th>
                <td>{{user.date_joined}}</td>
            </tr>
            <tr>
                <th>지역</th>
                <td>{{user.profile.location}}</td>
            </tr>
            <tr>
                <th>소개</th>
                <td>{{user.profile.bio}}</td>
            </tr>
            <tr>
                <th>생일</th>
                <td>{{user.profile.birth_at}}</td>
            </tr>
        </table>
    </div>
    <div class="card-action">
        <a href="#" class="red white-text btn disabled">개인정보 수정</a>
        <a href="#" class="red white-text btn disabled">탈퇴하기</a>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends 'accounts/layout.html' %}
{% block content %}
<nav>
    <div class="nav-wrapper" style="margin-left: 16px;">
        <div class="col">
            <a href="/" class="breadcrumb"><i class="material-icons">home</i></a>
            <span class="breadcrumb">회원 가입</span>
        </div>
    </div>
</nav>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">회원 가입</span>
        <form method="post">
            {% csrf_token %}
            <table style="margin-bottom: 8px;">
                {{form.as_table}}
            </table>
            <button type="submit" class="btn">확인</button>
        </form>
    </div>
</div>
{% endblock %}

musics/templates/musics/detail.html
{% extends 'musics/layout.html' %}
{% block title %}Musics - {{album.title}}{% endblock %}
{% block content %}
<nav>
    <div class="nav-wrapper" style="margin-left: 16px;">
        <div class="col">
            <a href="/" class="breadcrumb"><i class="material-icons">home</i></a>
            <span class="breadcrumb">앨범 상세</span>
        </div>
    </div>
</nav>
<div class="card red lighten-2">
    <div class="row">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img src="{{album.cover.url}}">
                    <a class="disabled btn-floating halfway-fab waves-effect waves-light red hoverable"><i class="material-icons">favorite_border</i></a>
                </div>
                <div class="card-content">
                    <span class="card-title red-text">{{album.title}}</span>
                    <table class="bordered centered">
                        <colgroup>
                            <col width="25%">
                            <col width="75%">
                        </colgroup>
                        <tr>
                            <th>뮤지션</th>
                            <td><a href="{% url 'musics:mdetail' album.musician %}">{{album.musician}}</a></td>
                        </tr>
                        <tr>
                            <th>발매일</th>
                            <td>{{album.release_at|date:'Y-m-d'}}</td>
                        </tr>
                        <tr>
                            <th>장르</th>
                            <td>{{album.genre}}</td>
                        </tr>
                        <tr>
                            <th>배급사</th>
                            <td>{{album.distribution}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            <div class="card">
                <div class="card-content">
                    <span class="card-title red-text">총 {{songs|length}}곡</span>
                    <table class="bordered">
                        <colgroup>
                            <col width="10%">
                            <col width="55%">
                            <col width="35%">
                        </colgroup>
                        <thead>
                            <tr>
                                <th>번호</th>
                                <th>곡명</th>
                                <th>뮤지션</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in songs %}
                            <tr>
                                <td>{{song.order}}</td>
                                <td>{{song.title}}</td>
                                <td>{{song.musician}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-action">
                    <a href="#" class="red white-text btn disabled"><i class="material-icons left">play_circle_outline</i> 미리 듣기</a>
                    <a href="#" class="red white-text btn disabled"><i class="material-icons left">file_download</i> 음원 구매하기</a>
                    <a href="#" class="red white-text btn disabled"><i class="material-icons left">card_giftcard</i> 선물하기</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">앨범 소개</span>
        {{album.introduction|linebreaks}}
    </div>
</div>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">앨범 한마디</span>
        {% if not user.is_authenticated %}
        <ul class="collection">
            <li class="collection-item center-align">댓글을 작성하려면 <a href="{% url 'accounts:login' %}?next={{request.path}}">로그인</a>해주세요.</li>
        </ul>
        {% else %}
        <form action="{% url 'musics:save_comment' album.pk %}" method="post">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <p class="right-align"><button type="submit" class="waves-effect waves-light btn red lighten-2">댓글 올리기</button></p>
        </form>
        {% endif %}
        <ul class="collection">
        {% if comments %}
            {% for comment in album.comment_set.all %}
            <li class="collection-item">{{comment.message}}
                <small>by {{comment.user}} at {{comment.created_at}}</small>
            </li>
            {% endfor %}
        {% else %}
            <li class="collection-item center-align">댓글이 하나도 없습니다.</li>
        {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

musics/templates/musics/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/minty/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"> -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
        <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <div class="navbar-fixed">
            <nav>
                <div class="nav-wrapper">
                    <a href="{% url 'musics:list' %}" class="brand-logo right">Musics</a>
                    <ul id="nav-mobile" class="left hide-on-med-and-down">
                        <li><a href="#!">로그인</a></li>
                    </ul>
                    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                </div>
            </nav>
        </div>
        <ul id="slide-out" class="sidenav">
            <li>
                <div class="user-view">
                    <div class="background"><img src="images/office.jpg"></div>
                    <a href="#user"><img class="circle" src="images/yuna.jpg"></a>
                    <a href="#name"><span class="white-text name">John Doe</span></a>
                    <a href="#email"><span class="white-text email">jdandturk@gmail.com</span></a>
                </div>
            </li>
            <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
            <li><a href="#!">Second Link</a></li>
            <li><div class="divider"></div></li>
            <li><a class="subheader">Subheader</a></li>
            <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
        </ul>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <div class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h5 class="white-text">Musics</h5>
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">이용약관</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">개인정보 처리방침</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">고객센터</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    &copy; 2018 Musics All rights reserved.
                </div>
            </div>
        </div>
        <script type="text/javascript">
            M.AutoInit();
            $('.carousel').carousel({
                dist : -20
            });
        </script>
    </body>
</html>

musics/templates/musics/list.html
{% extends 'musics/layout.html' %}
{% block title %}Musics{% endblock %}
{% block extra_head %}
<style type="text/css">
    .album-cover {
        max-width : 216px;
        max-height : 216px;
        margin: 0 auto;
    }
</style>
{% endblock %}
{% block content %}
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">최신 음악</span>
        <div class="carousel">
            {% for album in albums %}
            <a class="carousel-item hoverable" href="{% url 'musics:detail' album.id %}">
                <img src="{{album.cover.url}}" class="album-cover">
                <p>{{album.title}}</p>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">앨범 목록</span>
    </div>
    <div class="row">
        {% for album in albums %}
        <div class="col m3 s6">
            <div class="card hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <a href="{% url 'musics:detail' album.id %}"><img class="activator album-cover" src="{{album.cover.url}}"></a>
                </div>
                <div class="card-content">
                    <a href="{% url 'musics:detail' album.id %}">
                        <p class="truncate">{{album.title}}<br>{{album.musician}}</p>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

musics/templates/musics/mdetail.html
{% extends 'musics/layout.html' %}
{% block title %}Musics - {{musician.name}}{% endblock %}
{% block extra_head %}
<style type="text/css">
    .album-cover {
        max-width : 216px;
        max-height : 216px;
        margin: 0 auto;
    }
</style>
{% endblock %}
{% block content %}
<nav>
    <div class="nav-wrapper" style="margin-left: 16px;">
        <div class="col">
            <a href="/" class="breadcrumb"><i class="material-icons">home</i></a>
            <span class="breadcrumb">뮤지션 상세</span>
        </div>
    </div>
</nav>
<div class="card red lighten-2">
    <div class="row">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                    <span class="card-title red-text">{{musician.name}}</span>
                    <table class="bordered centered">
                        <colgroup>
                            <col width="25%">
                            <col width="75%">
                        </colgroup>
                        <tr>
                            <th>데뷔일</th>
                            <td>{{musician.debut_at|date:'Y-m-d'}}</td>
                        </tr>
                        <tr>
                            <th>소속사</th>
                            <td>{{musician.agency}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            <div class="card">
                <div class="card-content">
                    <span class="card-title red-text">전체 {{albums|length}}</span>
                    <div class="carousel">
                        {% for album in albums %}
                        <a class="carousel-item hoverable" href="{% url 'musics:detail' album.id %}">
                            <img src="{{album.cover.url}}" class="album-cover">
                            <p>{{album.title}}</p>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <span class="card-title red-text">뮤지션 소개</span>
        {% if not musician.introduction %}
        <p class="center-align" style="margin: 20px;">소개가 없습니다.</p>
        {% else %}
        {{musician.introduction|linebreaks}}
        {% endif %}
    </div>
</div>
{% endblock %}

portalsite/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/minty/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"> -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
        <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <div class="navbar-fixed">
            <nav>
                <div class="nav-wrapper">
                    <a href="{% url 'musics:list' %}" class="brand-logo right">Musics</a>
                    <ul id="nav-mobile" class="left hide-on-med-and-down">
                        {% if not user.is_authenticated %}
                        <li><a href="{% url 'accounts:login' %}?next={{request.path}}">로그인</a></li>
                        <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:profile' %}">마이페이지</a></li>
                        <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
                        {% endif %}
                    </ul>
                    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                </div>
            </nav>
        </div>
        <ul id="slide-out" class="sidenav">
            {% if user.is_authenticated %}
            <li>
                <div class="user-view red lighten-2">
                    <span class="white-text name">{{user.username}}</span>
                    <span class="white-text email">{{user.email}}</span>
                </div>
            </li>
            {% endif %}
            {% if not user.is_authenticated %}
            <li><a class="waves-effect" href="{% url 'accounts:login' %}?next={{request.path}}">로그인</a></li>
            <li><div class="divider"></div></li>
            <li><a class="waves-effect" href="{% url 'accounts:signup' %}">회원가입</a></li>
            {% else %}
            <li><a class="waves-effect" href="{% url 'accounts:profile' %}">마이페이지</a></li>
            <li><div class="divider"></div></li>
            <li><a class="waves-effect" href="{% url 'accounts:logout' %}?next={{request.path}}">로그아웃</a></li>
            {% endif %}
        </ul>
        <div class="container" style="margin-top: 8px;">
            {% block content %}
            {% endblock %}
        </div>
        <div class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h5 class="white-text">Musics</h5>
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">이용약관</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">개인정보 처리방침</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">고객센터</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    &copy; 2018 Musics All rights reserved.
                </div>
            </div>
        </div>
        <script type="text/javascript">
            M.AutoInit();
            $('.carousel').carousel({
                dist : -20
            });
        </script>
    </body>
</html>